SRCDIR := 
BUILDDIR := obj/
LIBDIR := lib/
APPDIR := bin/
LIBSRCDIR := $(SRCDIR)
APPSRCDIR := $(SRCDIR)
INCDIR := $(LIBSRCDIR)
CREATEDIR := .create

LIB_NAME := ocscmdline
LIB_STATIC := 1
LIB_SRCS := $(wildcard $(LIBSRCDIR)*.c)
LIB_INC := $(wildcard $(LIBSRCDIR)*.h)
LIB_VERSION :=
LIB_DEPLIB :=

APP_NAME :=
APP_SRCS :=
APP_DEPLIB :=


include ../ocs.mk