SRCDIR := 
BUILDDIR := obj/
LIBDIR := lib/
APPDIR := bin/
LIBSRCDIR := $(SRCDIR)
APPSRCDIR := $(SRCDIR)
INCDIR := $(LIBSRCDIR)
CREATEDIR := .create

LIB_NAME :=
LIB_STATIC :=
LIB_SRCS :=
LIB_INC :=
LIB_VERSION :=
LIB_DEPLIB :=

APP_NAME := ocs-fru
APP_SRCS := $(wildcard $(APPSRCDIR)*.c)
APP_DEPLIB := ocslog ocsfrui2c


include ../ocs.mk