# Copyright (C) Microsoft Corporation. All rights reserved.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# Note 1: There is a space character after every number for the formatting
# in scripts to work right. Do not remove them.
#
# Note 2: ROLLING-BUILD-ID will be automatically updated by updatebuildver
# script. This file needs to be manually checked in to maintain increments.

#define ROLLING_BUILD_ID            412 

// U-Boot version
#define BSP_VERSION_MAJOR           1 
#define BSP_VERSION_MINOR           0 
#define BSP_VERSION_REVISION        3 
#define BSP_PATCH_MD5SUM            47159e165ba4f6b6f14896ee849e37f2

// Devicetree version
#define DTS_VERSION_MAJOR           1 
#define DTS_VERSION_MINOR           0 
#define DTS_VERSION_REVISION        3 

// Kernel version
#define KER_VERSION_MAJOR           1 
#define KER_VERSION_MINOR           0 
#define KER_VERSION_REVISION        3 

// Root file system version
#define RFS_VERSION_MAJOR           1 
#define RFS_VERSION_MINOR           0 
#define RFS_VERSION_REVISION        3 

// Build package version
#define PKG_VERSION_MAJOR           1 
#define PKG_VERSION_MINOR           0 
#define PKG_VERSION_REVISION        3 
